# Generated by Django 5.1 on 2024-09-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Tittle2security',
            new_name='Tittle_2_security',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Tittle1web',
        ),
        migrations.AddField(
            model_name='service',
            name='Tittle_1_web',
            field=models.CharField(default=2, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='Research',
            field=models.CharField(max_length=500),
        ),
    ]
