# Generated by Django 5.1 on 2024-09-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sultan', '0002_rename_tittle2security_service_tittle_2_security_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Tittle_2_security',
            new_name='Tittle2_security',
        ),
    ]
