# Generated by Django 5.1 on 2024-09-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultan', '0003_rename_tittle_2_security_service_tittle2_security'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='Degree',
        ),
        migrations.RemoveField(
            model_name='education',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='education',
            name='History',
        ),
        migrations.RemoveField(
            model_name='education',
            name='Tittle',
        ),
        migrations.AddField(
            model_name='education',
            name='Degree_department',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='Description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='Institute',
            field=models.CharField(max_length=500),
        ),
    ]
