# Generated by Django 5.1 on 2024-09-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sultan', '0004_remove_education_degree_remove_education_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Tittle',
        ),
    ]
