# Generated by Django 5.1 on 2024-09-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sultan', '0006_delete_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='Name',
            new_name='Company_name',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='Tittle',
        ),
        migrations.RemoveField(
            model_name='resarch',
            name='Mention',
        ),
        migrations.RemoveField(
            model_name='resarch',
            name='Tittle',
        ),
    ]
