# Generated by Django 5.1 on 2024-10-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultan', '0007_rename_name_experience_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='S_image',
            field=models.ImageField(default=1, upload_to='my_images/'),
            preserve_default=False,
        ),
    ]
