# Generated by Django 5.1 on 2024-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABOUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=500)),
                ('Occupation', models.CharField(max_length=250)),
                ('Phone', models.CharField(max_length=520)),
                ('Email', models.CharField(max_length=500)),
                ('Nationality', models.CharField(max_length=500)),
            ],
        ),
    ]
