# Generated by Django 5.1 on 2024-09-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midterm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('Institute', models.CharField(max_length=250)),
                ('Session', models.CharField(max_length=250)),
                ('Result', models.CharField(max_length=250)),
            ],
        ),
    ]
